[package]
name = "rufendec"
version = "0.1.0"
edition = "2021"
description = "Rufendec aka (Rust File Encryptor-Decryptor) is a CLI utility tool which helps you to do AES-256 Encryption and Decryption on specified directories/folders and retain the complete directory structure of the source directory files you provide into the target directory"
authors = ["Venkatesh Omkaram"]
license = "MIT"
repository = "https://github.com/omkarium/rufendec"
keywords = ["aes", "aes-256", "file-encryption-tool"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-aes = "0.1.0"
clap = { version = "4.4.11", features = ["derive"] }
lazy_static = "1.4.0"
rayon = "1.8.0"
chrono = "0.4.31"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
