[self]
name = "rufendec"
version = "0.9.2"
description = "Rufendec is a lightweight CLI tool for AES-256 encryption and decryption, preserving file names and directory structure. With support for ECB/GCM modes, it simplifies securing and restoring files with ease, all powered by Rust."
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2023 Venkatesh Omkaram",
  "Copyright 2023 Venkatesh Omkaram",
]
authors = ["Venkatesh Omkaram"]
repository = "https://github.com/omkarium/rufendec"
